site_name: ColdFront
docs_dir: 'pages'
site_description: 'HPC Resource Allocation Management System'
site_url: 'https://github.com/ubccr/coldfront'
copyright: 'Copyright &copy; 2021 Center for Computational Research, University at Buffalo'
repo_name: 'ubccr/coldfront'
repo_url: 'https://github.com/ubccr/coldfront'
edit_uri: ''

theme:
  name: 'readthedocs'
  highlightjs: true
  prev_next_buttons_location: both
  navigation_depth: 4
  logo: 'images/logo.png'
  favicon: 'images/favicon.png'

markdown_extensions:
  - footnotes
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde

nav:
    - What is ColdFront?: index.md
    - Introduction: intro.md
    - Quick Start Install: quickstart.md
    - Plugins: plugin.md
    - Demos: demos.md
    - User Manual:
        - Projects: manual/projects/projects.md
            - Grants: manual/projects/grants.md
            - Publications: manual/projects/publications.md
            - Research Outputs: manual/projects/researchoutputs.md
            - Project Review: manual/projects/projectreview.md
        - Resources: manual/resources/resources.md
        - Allocations: manual/allocations/allocations.md
        - Users: manual/users/users.md
            - PI: manual/users/pi.md
            - Manager: manual/users/manager.md
            - Staff: manual/users/staff.md
            - Director: manual/users/director.md
            - Billing: manual/users/biling.md
            - System Administrators: manual/users/sysadmins.md
