site_name: ColdFront
docs_dir: 'pages'
site_description: 'HPC Resource Allocation Management System'
site_url: 'https://github.com/ubccr/coldfront'
copyright: 'Copyright &copy; 2021 Center for Computational Research, University at Buffalo'
repo_name: 'ubccr/coldfront'
repo_url: 'https://github.com/ubccr/coldfront'
edit_uri: ''

theme:
  name: 'readthedocs'
  logo: 'images/logo.png'
  favicon: 'images/favicon.png'

markdown_extensions:
  - footnotes
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde

nav:
    - What is ColdFront?: index.md
    - Introduction: intro.md
    - Quick Start Install: quickstart.md
    - Plugins: plugin.md
    - Demos: demos.md
    - User Manual:
        - Projects: manual/projects/projects.md
        - Resources: manual/resources/resources.md
        - Allocations: manual/allocations/allocations.md
        - Users: manual/users/users.md
